version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 587027614473.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t eks-repo .
      - docker tag eks-repo:latest 587027614473.dkr.ecr.us-east-1.amazonaws.com/eks-repo:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 587027614473.dkr.ecr.us-east-1.amazonaws.com/eks-repo:latest
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f k8s-deployment.yml

artifacts:
  files: k8s-deployment.yml
